
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_traditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_tags ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.discussion_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_likes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.library_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reading_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_path_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_paths ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.saved_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_posts ENABLE ROW LEVEL SECURITY;